AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-duckdb-stac

Parameters:
  LambdaTimeout:
    Default: 30
    Description: 'Max lambda execution time in seconds'
    Type: Number

  LambdaMemorySize:
    Default: 2048
    Description: 'Max lambda Memory in Mb'
    Type: Number

  StacParquetLocations:
    Default: |
            {
              "glo-30-hand": "s3://asf-stac-bucket/glo-30-hand.parquet",
              "sentinel-1-global-coherence": "s3://asf-stac-bucket/sentinel-1-global-coherence.parquet"
            }
    Description: 'JSON Object pointing to collections Location of'
    Type: String

  StacBucketName:
    Description: 'Optional Bucket to grant lambda access to'
    Type: String
    Default: 'asf-stac-bucket'

  ApiCustomDomainName:
    Type: String
    Description: "Custom domain for the HTTP API (e.g., api.example.com)"

  AcmCertificateArn:
    Type: String
    Description: "ACM certificate ARN in the SAME region as this API (imported cert)"

  ApiBasePath:
    Type: String
    Default: ""
    Description: "Optional base path for API mapping (leave empty for root mapping)"

Conditions:
  IsS3: !Not [!Equals [!Ref StacBucketName, ""]]
  HasBasePath: !Not [!Equals [!Ref ApiBasePath, ""]]

Resources:
  DuckDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: duck-dependencies-layer
      Description: Python dependencies DuckStac functions
      ContentUri: ./
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11

  ExplicitApiHttpApi:
    Type: AWS::Serverless::HttpApi
    # NOTE: We do NOT set the "Domain" property here so we can
    # create explicit DomainName/ApiMapping resources and export
    # their DNS targets for external DNS providers.

  DuckStacFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_root/
      Handler: stac_fastapi.duckdb.app.handler
      Runtime: python3.11
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Layers:
        - !Ref DuckDependenciesLayer
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAC_FILE_PATH: /var/task/data/stac_collections
          BACKEND: duckdb
          TZ: UTC             # Avoid Timezone Error
          HOME: "/tmp/"       # Otherwise DuckDB breaks
          PARQUET_URLS_JSON: !Ref StacParquetLocations
      Policies:
        - S3FullAccessPolicy:
            Condition: IsS3
            BucketName: !Ref StacBucketName
      Events:
        DuckStac:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExplicitApiHttpApi
            Path: /{proxy+}
            Method: ANY

  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref ApiCustomDomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref AcmCertificateArn
          EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2

  ApiDomainMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref ExplicitApiHttpApi
      DomainName: !Ref ApiDomainName
      Stage: '$default'
      ApiMappingKey: !If [HasBasePath, !Ref ApiBasePath, !Ref 'AWS::NoValue']

Outputs:
  DuckStacApi:
    Description: "Execute-API URL for $default stage"
    Value: !Sub "https://${ExplicitApiHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

  CustomDomainName:
    Description: "Custom domain for the API"
    Value: !Ref ApiCustomDomainName

  CustomDomainBasePath:
    Description: "Base path mapping (empty => root)"
    Value: !Ref ApiBasePath

  ApiGatewayRegionalDomainName:
    Description: "Target DNS name for your external ALIAS/ANAME/CNAME"
    Value: !GetAtt ApiDomainName.RegionalDomainName

  ApiGatewayRegionalHostedZoneId:
    Description: "HostedZoneId for ALIAS records (some DNS providers need this)"
    Value: !GetAtt ApiDomainName.RegionalHostedZoneId

  CustomDomainInvokeUrl:
    Description: "Final HTTPS URL (works after your external DNS points to the RegionalDomainName)"
    Value: !If
      - HasBasePath
      - !Sub "https://${ApiCustomDomainName}/${ApiBasePath}"
      - !Sub "https://${ApiCustomDomainName}"
