name: Check that SAM can build successfully

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-with-sam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          create-args: >-
            python=3.11

      - name: Build in conda environment
        shell: bash -l {0}
        run: |
          make build
